### ISSUE TITLE
Responsive?

### ISSUE THREAD

**Issue by devbau** [Nitrino/flatly_light_redmine#16]
How about multi-device support? Is Flatly light theme responsive?

**Comment by agramian** [comment]
Any updates here? I love this theme and it would be even better if I could easily view and edit things using my phone.  If you don't plan on getting to it soon I can help out or work on this.

**Comment by Nitrino** [comment]
@agramian Unfortunately I'm not working with redmine not always have time to improve. I'll be glad to any pull requests
