### ISSUE TITLE
Problem with wrapping menu options

### ISSUE THREAD

**Issue by dgutkowsky** [Nitrino/flatly_light_redmine#37]
when I move the mouse it's trying to reorient itself - please look at the screenshots

![image 001](https://cloud.githubusercontent.com/assets/4732829/4495962/d4635456-4a60-11e4-870e-322afdf4a236.png)

![image 002](https://cloud.githubusercontent.com/assets/4732829/4495965/d5dfa64a-4a60-11e4-8e43-f7fb3b442ddb.png)

**Comment by Nitrino** [comment]
Now there is no such problem, sorry
