### ISSUE TITLE
the variable to deactivate left bar make only the button disappear

### ISSUE THREAD

**Issue by antoine-morisseau** [Nitrino/flatly_light_redmine#44]
![image](https://cloud.githubusercontent.com/assets/3832837/5285000/d0231226-7b18-11e4-917e-afa3e2f5abf2.png)

Information about redmine : 

![image](https://cloud.githubusercontent.com/assets/3832837/5285028/fb1c3bc4-7b18-11e4-9cdb-1433da7853cf.png)

**Comment by pousterlus** [comment]
I think this is fixed by now...
In my Redmine 3.4.2.stable, it seems it's working well.

-- 
Léo.

**Comment by Nitrino** [comment]
@pousterlus Thanks for feedback!
