### ISSUE TITLE
Improvment and fix location of project quick jump box

### ISSUE THREAD

**Issue by antoine-morisseau** [Nitrino/flatly_light_redmine#46]
Hello,
First of all very nice good looking theme !
I think it can become a very much powerfull theme if more functionnality added.
We have on latest version of chrome (not tested on firefox and IE) a misplacement of the quick jump box i think it's just a css issue but i'm not a pro in it... is it possible to resolve it ?

![image](https://cloud.githubusercontent.com/assets/3832837/5296058/bfccb97c-7b9f-11e4-846d-498275e5a98c.png)

And with that is it possible to improve the style of this quick jump box to this kind ?

![image](https://cloud.githubusercontent.com/assets/3832837/5296068/e5b66962-7b9f-11e4-9a42-24ed6ae45509.png)

Regards,

**Comment by Nitrino** [comment]
Sorry. Now it's fixed.
