### ISSUE TITLE
toggle_check.png is almost invisible

### ISSUE THREAD

**Issue by owlen** [Nitrino/flatly_light_redmine#48]
The toggle check image is white on transparent, making it invisble or close to invisible on my setup.
Here it's hardly seen on dark rows, and invisible on white ones:

![image](https://cloud.githubusercontent.com/assets/5638865/6445916/1a462784-c110-11e4-894f-111e529acb1f.png)

I'm using chromium Version 40.0.2214.111 on Kubuntu.

**Comment by owlen** [comment]
btw, I switched to using this: http://www.veryicon.com/icons/internet--web/web-development-3/action-check-grey-thin.html and it looks well. 
It comes with Creative Commons Attribution 3.0 License.

![image](https://cloud.githubusercontent.com/assets/5638865/6446213/406213ae-c112-11e4-8f91-c63b97d1746c.png)

**Comment by Nitrino** [comment]
At the moment I do not see such a problem. If it is still relevant, tell us more details
