### ISSUE TITLE
Please, clarify the license on this package.

### ISSUE THREAD

**Issue by othyro** [Nitrino/flatly_light_redmine#53]
Greetings,

Could you please clarify the license on this package? I would like to import it to pkgsrc. It seems to work with redmine-3.0.3, BTW.

Best regards,

**Comment by Nitrino** [comment]
This theme is released under the MIT license. Feel free to use any of their purposes.
Added license file https://github.com/Nitrino/flatly_light_redmine/blob/master/LICENSE
If you have ideas or want contribute, then I will gladly accept them.
