### ISSUE TITLE
Suggestion - Separate projects in project list

### ISSUE THREAD

**Issue by LeGiangAnh** [Nitrino/flatly_light_redmine#57]
Hi,

I suggest that we should separate the projects in project list:
![image](https://cloud.githubusercontent.com/assets/5027251/13037959/73beb04e-d3be-11e5-8e24-af3098e1dc4f.png)

It sticks together currently which is not nice.
Example: 
![image](https://cloud.githubusercontent.com/assets/5027251/13037976/9d93c454-d3be-11e5-8ddc-c27fc1b9bcec.png)

**Comment by pousterlus** [comment]
Hi,

It would be great indeed, that's the only missing thing in that theme.
Did you find a way to do it ?

-- 
Léo.

**Comment by Nitrino** [comment]
Hi,
Sorry, I was very busy and some time did not maintain project.
I added separate projects in new version v0.1.1

![image](https://cloud.githubusercontent.com/assets/1032291/18122182/7282d6f4-6f92-11e6-817d-a7b6a943a71a.png)

**Comment by pousterlus** [comment]
Wow, Nitrino, that's a fine job.
Don't apologize about being busy, you're helping when you can.

-- 
Léo.
