### ISSUE TITLE
Responsive design is broken with Redmine 3.4

### ISSUE THREAD

**Issue by Kyoshiro-san** [Nitrino/flatly_light_redmine#59]
Hello,

Using Redmine 3.4, when you reduce the display width redmine goes to tablet/phone mode and changes the top bar. The theme does not seem to know about it and the display is broken.

See attached pictures.
![responsive-broken](https://user-images.githubusercontent.com/988293/32845305-b20ba66e-ca24-11e7-9730-7835c21fdb46.png)
![responsive-ok](https://user-images.githubusercontent.com/988293/32845357-d1b8166e-ca24-11e7-9667-dbde4750c1ae.png)

Cheers

**Comment by Nitrino** [comment]
Now in v0.2.1, I disabled the response styles of redmine. 
In the future, I'll think about a responsive version of this theme
