### ISSUE TITLE
Redmine 3.4.3  Project Page display errors

### ISSUE THREAD

**Issue by Saliva520319** [Nitrino/flatly_light_redmine#61]
- Docker-ce 17.09, images official redmine:3.4.3
- when I add a project , the css style does not fit well. See pics below.
![2017-12-22 10 55 13](https://user-images.githubusercontent.com/11515867/34283434-a5fe8f5e-e706-11e7-92c1-4748290d3b67.png)

**Comment by Saliva520319** [comment]
Sorry for my poor English. Hope you can understand what I'm saying.

**Comment by Nitrino** [comment]
thanks for the feedback.
I'll see it in the coming days

**Comment by Nitrino** [comment]
fixed in v0.2.1
