### ISSUE TITLE
Slowness on downloads fonts

### ISSUE THREAD

**Issue by rachelbullmann** [Nitrino/flatly_light_redmine#62]
Hi, my company has a proxy that causes slow loading of fonts, and sometimes it crashes redmine when the theme is enabled, is there any way to store the fonts so they are not downloaded every time?

the display is great, it just does not work well inside my company network and I would like to get around this if possible.

Thank you and congratulations for the theme.

**Comment by Nitrino** [comment]
Hi. 
Fonts for this theme are stored on your server, probably a problem in the outbound channel of your network.

I also worried about the font size and I will soon make it lightweight. when this happens, I will report on this topic.
