### ISSUE TITLE
register for account disappears

### ISSUE THREAD

**Issue by strhuan** [Nitrino/flatly_light_redmine#63]
if you enable Authentication required under setting  Authentication
the register disappears
![screenshot from 2018-08-10 15-11-25](https://user-images.githubusercontent.com/1926887/43959629-be564a92-9caf-11e8-8848-b009cf3673cf.png)
if i disable it comes back again
![screenshot from 2018-08-10 15-12-55](https://user-images.githubusercontent.com/1926887/43959757-2f57bf8c-9cb0-11e8-944a-c320b4a90d7f.png)

**Comment by Nitrino** [comment]
Sorry for the long response, I released a new version fixing this bug.
https://github.com/Nitrino/flatly_light_redmine/releases/tag/v0.2.2
