### ISSUE TITLE
problem with DMSF plugin

### ISSUE THREAD

**Issue by PavelBaco** [Nitrino/flatly_light_redmine#65]
Hi,

great theme, but in DMSF plugin dont display column name.
![redmine-classic](https://user-images.githubusercontent.com/44222332/47501746-87b74980-d866-11e8-91c5-d13ecce5aee3.PNG)
![redmine-flatly](https://user-images.githubusercontent.com/44222332/47501747-87b74980-d866-11e8-93f4-e80fa019d624.PNG)
Any idea how can i fix it?

**Comment by Nitrino** [comment]
@PavelBaco Hi. 
I created a [new version](https://github.com/Nitrino/flatly_light_redmine/releases/tag/v0.2.3) fixing this bug.
Thanks for feedback
